# Default configuration for field delineation training

# Model configuration
model:
  arch: 'unetplusplus'
  encoder: 'resnet152'
  encoder_weights: 'imagenet'
  in_channels: 9
  out_channels: 3

# Training configuration
training:
  max_epochs: 30
  batch_size: 48
  learning_rate: 0.05
  batch_per_epoch: 200
  accumulate_grad_batches: 16
  precision: "16-mixed"

# Loss configuration
losses:
  loss_1: 'DiceLoss'
  loss_2: 'ComboLoss'
  loss_3: 'BCELoss'
  params_1:
    mode: 'multilabel'
    from_logits: true
  params_2:
    smoothing: 0.1
    alpha: 0.5
    ce_ratio: 0.5
  params_3: {}
  weight_1: 0.78
  weight_2: 0.0
  weight_3: 0.81

# Dataset configuration
data:
  dataset_type: 'MyanmarSatellite'
  train_dir: '../Datasets/MyanmarAnnotations/Resolution_0_5/Masks/Cropped/Train/'
  val_dir: '../Datasets/MyanmarAnnotations/Resolution_0_5/Masks/Cropped/Val/'
  test_dir: '../Datasets/MyanmarAnnotations/Resolution_0_5/Masks/Cropped/Val/'
  channels: 9
  augment: true
  cache_data: false

# Logging configuration
logging:
  project: 'Finetuning'
  entity: 'seonghahcho'
  log_model: false

# Checkpoint configuration
checkpoint:
  checkpoint_path: null
  save_top_k: 3
  monitor: 'val loss'
  mode: 'min'